AL:
  budget: 0
  initial_labeled: 0.1
  query: 0.02
  query_strategy: "RandomQuery"

Dataset:
  name: "ISIC"
  data_dir: "data/ISICPreprocessed"
  batch_size: 16
  num_workers: 3
  input_size: 1024

Training:
  output_dir: "Baseline"
  device: "cuda:0"
  iter_max: 30000
  iter_valid: 100
  early_stop_patience: 10000
  lr: 1.0e-3
  lr_gamma: 0.5
  ReduceLROnPlateau_patience: 20
  weight_decay: 1.0e-5
  seed: 3407
  rampup_start: 2000
  rampup_end: 35000
  regularize_w: 0.1


Network:
  class_num: 2
  ndf: 16
  in_chns: 3
  feature_grps: 1
  norm_type: [ "instance_norm", "instance_norm" ]
  acti_func: "relu"
  dropout: true
  deep_supervision: "none" #normal grouped none
  loose_sup: false
  class_focus_ensemble: false

